### ISSUE TITLE
StringExtensions.ConvertToEnum should specify enum constraint on type argument

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.Extensions#7]
This method was written back before it was possible to specify a constraint on a type argument requiring it to be an enum. (The inability to do this was utterly inexplicable. When challenged on it Eric Lippert wheeled out the usual "every feature starts with a negative score" spiel...but the whole point of that argument is that a feature needs to justify its costs. The weird thing about enum type constraints is that the compiler used to go out of its way to prevent them. In general you can specify any base type as a constraint, but the C# compiler used to block specifically `System.Enum` and `System.Delegate`. So really his argument made a strong case for being *allowed* to use these as constraints.)

Since C# 7.3 you can now specify a constraint requiring a type to derive from `System.Enum`. This method should use that.

**Comment by mwadams** [comment]
I propose removing this as there are now strongly typed conversions in `Enum.Parse<>`
