### ISSUE TITLE
StringExtensions.FirstNCharacters odd ellipsis handling

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.Extensions#8]
TBH I'm not convinced we want this method at all. If we do keep it, it's badly named: if I want the "first N characters" of a string I'll use `Substring`; this method apparently exists to truncate a string optionally adding an ellipsis, from which I conclude that it's probably intended for when you want to display the string in a fixed-size field that might be too narrow, although it's hard to be sure.

If it is for display purposes it's somewhat ill-conceived: almost all GUIs these days (web or desktop) use proprotional fonts, so truncating strings to make them fit requires you to take character widths into account. (It might be necessary to truncate "WWWWW" but not "llllll" even though the latter is 'shorter' as `string.Length` sees it.) Normally you achieve this sort of truncation through styling.

But possible wrongness of the method (and its arguable unsuitability as an extension method) notwithstanding it appears to make string length calculations based on the assumption that an ellipsis is three characters (which it usually is..., unless it's the Unicode ellipsis character…), but when it adds an ellipsis, it just adds ".." (i.e., only two dots).

**Comment by HowardvanRooijen** [comment]
I think this was the 2013 way of solving the problem you describe. It can now be solved more easily with CSS.

**Comment by endjin-github** [comment]
I actually think it was a truncated synopsis of n characters for a particular use case. The two doors is a legacy of lack of attention to detail that I didn't change for fear of breaking those who depended on it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mwadams** [comment]
I propose removing this method.
